### ISSUE TITLE
Radarr Data Not Populating

### ISSUE THREAD

**Issue by Colorado4Wheeler** [custom-components/sensor.radarr_upcoming_media#19]
**Describe the Bug**
I can get Sonarr working, but Radarr doesn't work.  The built-in integration for Radarr works fine.  The sensor reports 'Online'.

**The Error**
I don't get an error, just no results.

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Yes, and when I put in a manual URL it works as expected:

```
http://10.1.200.1:7878/api/calendar?apikey=3a2611d25472470e97319835f1d5f46c&start=2021-10-31&end=2022-05-15
```

**What data does the sensor display if any?**
The state attributes of the sensor.radarr_upcoming_media is:
```
data:
  - title_default: $title
    line1_default: $release
    line2_default: $genres
    line3_default: $rating - $runtime
    line4_default: $studio
    icon: mdi:arrow-down-bold
friendly_name: Radarr_Upcoming_Media
```
**What displays when visiting the API URL from the troubleshooting guide?**
Full JSON report of all upcoming movies.

**Does the default Home Assistant Radarr component work for you?**
Works perfectly.

**Home Assistant Version**
core-2021.11.5

**Additional Context**
Sensor config:

```
- platform: radarr_upcoming_media
  api_key: 3a2611d25472470e97319835f1d5f46c
  host: 10.1.200.1
  port: 7878
  days: 14
  ssl: false
  theaters: false
  max: 10
```
